config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # get "tasks", to: "tasks#index"
  # get "tasks/new", to: "tasks#new"
  # get "tasks/:id", to: "tasks#show", as: "task"
  # post "tasks", to: "tasks#create"
  # get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  # patch "tasks/:id", to: "tasks#update"
  # delete "tasks/:id", to: "tasks#destroy"
  root "tasks#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed unless @task.new_record? %>
    <%= f.check_box :completed unless @task.new_record? %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <%= render "form", restaurant: @restaurant %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
    <li>
      <i class="fa-regular fa-square<%= '-check' if task.completed %>"></i> <%= link_to task.title, task_path(task) %> · <%= link_to "Delete", task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </li>
    <% end %>
  </ul>
  <%= link_to "Add a new task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <p>This task is <%= @task.completed ? "completed" : "not completed yet" %></p>
  <p><%= link_to "Edit task", edit_task_path %></p>
  <p><%= link_to "Delete",
    task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %></p>
  <p><%= link_to "Back to tasks", root_path %></p>
</div>